CREATE TABLE nutrients (
    id SERIAL PRIMARY KEY,
    food_name TEXT,
    serving_size_g DOUBLE PRECISION,
    calories_kcal DOUBLE PRECISION,
    protein_g DOUBLE PRECISION,
    fat_g DOUBLE PRECISION,
    carbohydrates_g DOUBLE PRECISION,
    fiber_g DOUBLE PRECISION,
    sugar_g DOUBLE PRECISION,
    water_g DOUBLE PRECISION,
    vitamin_a_mcg DOUBLE PRECISION,
    vitamin_b1_mg DOUBLE PRECISION,
    vitamin_b2_mg DOUBLE PRECISION,
    vitamin_b3_mg DOUBLE PRECISION,
    vitamin_b5_mg DOUBLE PRECISION,
    vitamin_b6_mg DOUBLE PRECISION,
    vitamin_b7_mcg DOUBLE PRECISION,
    vitamin_b9_mcg DOUBLE PRECISION,
    vitamin_b12_mcg DOUBLE PRECISION,
    vitamin_c_mg DOUBLE PRECISION,
    vitamin_d_mcg DOUBLE PRECISION,
    vitamin_e_mg DOUBLE PRECISION,
    vitamin_k_mcg DOUBLE PRECISION,
    calcium_mg DOUBLE PRECISION,
    iron_mg DOUBLE PRECISION,
    magnesium_mg DOUBLE PRECISION,
    phosphorus_mg DOUBLE PRECISION,
    potassium_mg DOUBLE PRECISION,
    sodium_mg DOUBLE PRECISION,
    zinc_mg DOUBLE PRECISION,
    copper_mg DOUBLE PRECISION,
    manganese_mg DOUBLE PRECISION,
    selenium_mcg DOUBLE PRECISION,
    iodine_mcg DOUBLE PRECISION,
    fluoride_mg DOUBLE PRECISION,
    choline_mg DOUBLE PRECISION,
    omega_3_g DOUBLE PRECISION,
    omega_6_g DOUBLE PRECISION,
    trans_fat_g DOUBLE PRECISION,
    saturated_fat_g DOUBLE PRECISION,
    monounsaturated_fat_g DOUBLE PRECISION,
    polyunsaturated_fat_g DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);
