services:

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d:Z
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  v:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - v-backups:/app/backups

    healthcheck:
      test: "healthcheck.sh || kill 1"
      interval: 10s
      retries: 3
      
volumes:
  v-backups:
