CREATE TABLE accounts (
    id BIGSERIAL PRIMARY KEY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    pin TEXT NOT NULL,
    pic TEXT NOT NULL,
    last_login_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    character_slots SMALLINT NOT NULL,
    gender SMALLINT NOT NULL,
    accepted_tos BOOLEAN NOT NULL,
    banned BOOLEAN NOT NULL,
    playing BOOLEAN NOT NULL
);

CREATE TABLE characters (
    id BIGSERIAL PRIMARY KEY,
    account BIGINT NOT NULL,
    world SMALLINT NOT NULL,
    ign TEXT NOT NULL,
    level SMALLINT NOT NULL,
    exp BIGINT NOT NULL,
    strength INTEGER NOT NULL,
    dexterity INTEGER NOT NULL,
    luck INTEGER NOT NULL,
    intelligence INTEGER NOT NULL,
    hp INTEGER NOT NULL,
    mp INTEGER NOT NULL,
    max_hp INTEGER NOT NULL,
    max_mp INTEGER NOT NULL,
    ap SMALLINT NOT NULL,
    fame SMALLINT NOT NULL,
    meso INTEGER NOT NULL,
    job SMALLINT NOT NULL,
    face INTEGER NOT NULL,
    hair INTEGER NOT NULL,
    hair_color INTEGER NOT NULL,
    skin INTEGER NOT NULL,
    gender SMALLINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    map INTEGER NOT NULL
);
